### ISSUE TITLE
Unused files to remove in Dockerfile

### ISSUE THREAD

**Issue by wizardjedi** [errordeveloper/dockerfile-oracle-java#3]
Hi,

there are a lot of files to be removed. Like sources, etc.

source: https://registry.hub.docker.com/u/jeanblanchard/busybox-java/dockerfile/

Magic comes in lines:
rm -rf /opt/jdk/_src.zip \
           /opt/jdk/lib/missioncontrol \
           /opt/jdk/lib/visualvm \
           /opt/jdk/lib/_javafx\* \
           /opt/jdk/jre/lib/plugin.jar \
           /opt/jdk/jre/lib/ext/jfxrt.jar \
           /opt/jdk/jre/bin/javaws \
           /opt/jdk/jre/lib/javaws.jar \
           /opt/jdk/jre/lib/desktop \
           /opt/jdk/jre/plugin \
           /opt/jdk/jre/lib/deploy\* \
           /opt/jdk/jre/lib/_javafx_ \
           /opt/jdk/jre/lib/_jfx_ \
           /opt/jdk/jre/lib/amd64/libdecora_sse.so \
           /opt/jdk/jre/lib/amd64/libprism__.so \
           /opt/jdk/jre/lib/amd64/libfxplugins.so \
           /opt/jdk/jre/lib/amd64/libglass.so \
           /opt/jdk/jre/lib/amd64/libgstreamer-lite.so \
           /opt/jdk/jre/lib/amd64/libjavafx_.so \
           /opt/jdk/jre/lib/amd64/libjfx*.so

/opt/jdk/ could be replaces with ${JAVA_HOME} in case of your Dockerfile. It could reduce image size.

**Comment by mrserverless** [comment]
actually this project is already slightly smaller than busybox-java

```
jeanblanchard/busybox-java          latest              906dc9067a40        3 weeks ago         160.2 MB
errordeveloper/oracle-jre           latest              183e41fe6d99        2 weeks ago         159.4 MB
```

Adding in the above long `rm -rf` line didn't really make much difference for me.

**Comment by mrserverless** [comment]
Actually now looking back, deleting those files could make a difference only if the images are [flattened](http://stackoverflow.com/questions/22713551/how-to-flatten-a-docker-image). Might have a go at this when I have some free time
